"""refactor_to_ingested_files

Revision ID: ee4052d195c3
Revises: a6523bbee66b
Create Date: 2026-08-14 11:53:06.386254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4052d195c3'
down_revision: Union[str, Sequence[str], None] = 'a6523bbee66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingested_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.Enum('FTP', 'Local', 'GDrive', 'Sharepoint', name='ingested_file_provider_type'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('physical_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('master_hash', sa.String(length=64), nullable=True),
    sa.Column('provider_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingested_files_dataset_id'), 'ingested_files', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_ingested_files_file_path'), 'ingested_files', ['file_path'], unique=False)
    op.create_index(op.f('ix_ingested_files_provider_hash'), 'ingested_files', ['provider_hash'], unique=False)
    op.create_index(op.f('ix_ingested_files_status'), 'ingested_files', ['status'], unique=False)
    op.create_index(op.f('ix_ingested_files_user_id'), 'ingested_files', ['user_id'], unique=False)
    op.drop_table('folders')
    op.drop_index(op.f('ix_dataset_folder_files_mapping_dataset_id'), table_name='dataset_folder_files_mapping')
    op.drop_index(op.f('ix_dataset_folder_files_mapping_file_id'), table_name='dataset_folder_files_mapping')
    op.drop_index(op.f('ix_dataset_folder_files_mapping_folder_id'), table_name='dataset_folder_files_mapping')
    op.drop_index(op.f('ix_dataset_folder_files_mapping_user_id'), table_name='dataset_folder_files_mapping')
    op.drop_table('dataset_folder_files_mapping')
    op.drop_index(op.f('ix_provider_hash_mappings_master_hash'), table_name='provider_hash_mappings')
    op.drop_index(op.f('ix_provider_hash_mappings_provider_file_id'), table_name='provider_hash_mappings')
    op.drop_index(op.f('ix_provider_hash_mappings_provider_hash'), table_name='provider_hash_mappings')
    op.drop_index(op.f('ix_provider_hash_mappings_provider_name'), table_name='provider_hash_mappings')
    op.drop_table('provider_hash_mappings')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_async_ingestion_jobs_dataset_id'), table_name='async_ingestion_jobs')
    op.drop_index(op.f('ix_async_ingestion_jobs_folder_id'), table_name='async_ingestion_jobs')
    op.drop_index(op.f('ix_async_ingestion_jobs_status'), table_name='async_ingestion_jobs')
    op.drop_index(op.f('ix_async_ingestion_jobs_user_id'), table_name='async_ingestion_jobs')
    op.drop_table('async_ingestion_jobs')
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.drop_column('datasets', 'content_type')
    op.drop_column('datasets', 'source_type')
    op.drop_column('datasets', 'format')
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('google_subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('otp_code_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('otp_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('otp_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('password_reset_token_hash', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_subject'), 'users', ['google_subject'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_google_subject'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'password_reset_expires_at')
    op.drop_column('users', 'password_reset_token_hash')
    op.drop_column('users', 'otp_attempts')
    op.drop_column('users', 'otp_code_expires_at')
    op.drop_column('users', 'otp_code_hash')
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'google_subject')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'username')
    op.add_column('datasets', sa.Column('format', sa.VARCHAR(length=255), nullable=True))
    op.add_column('datasets', sa.Column('source_type', sa.VARCHAR(length=255), nullable=True))
    op.add_column('datasets', sa.Column('content_type', sa.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.create_table('async_ingestion_jobs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('folder_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('source_url_or_id', sa.VARCHAR(length=500), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('progress_percentage', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('master_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('file_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('bytes_downloaded', sa.BIGINT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('total_bytes', sa.BIGINT(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_ingestion_jobs_user_id'), 'async_ingestion_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_async_ingestion_jobs_status'), 'async_ingestion_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_async_ingestion_jobs_folder_id'), 'async_ingestion_jobs', ['folder_id'], unique=False)
    op.create_index(op.f('ix_async_ingestion_jobs_dataset_id'), 'async_ingestion_jobs', ['dataset_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('folder_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), nullable=False),
    sa.Column('master_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('physical_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'folder_id', 'master_hash', name=op.f('uq_user_folder_master_hash'))
    )
    op.create_table('provider_hash_mappings',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('provider_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('provider_file_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('provider_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('master_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['master_hash'], ['uploaded_files.master_hash'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'provider_hash', name=op.f('uq_provider_name_hash'))
    )
    op.create_index(op.f('ix_provider_hash_mappings_provider_name'), 'provider_hash_mappings', ['provider_name'], unique=False)
    op.create_index(op.f('ix_provider_hash_mappings_provider_hash'), 'provider_hash_mappings', ['provider_hash'], unique=False)
    op.create_index(op.f('ix_provider_hash_mappings_provider_file_id'), 'provider_hash_mappings', ['provider_file_id'], unique=False)
    op.create_index(op.f('ix_provider_hash_mappings_master_hash'), 'provider_hash_mappings', ['master_hash'], unique=False)
    op.create_table('dataset_folder_files_mapping',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('dataset_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('folder_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('file_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'folder_id', 'file_id', name=op.f('uq_dataset_folder_file'))
    )
    op.create_index(op.f('ix_dataset_folder_files_mapping_user_id'), 'dataset_folder_files_mapping', ['user_id'], unique=False)
    op.create_index(op.f('ix_dataset_folder_files_mapping_folder_id'), 'dataset_folder_files_mapping', ['folder_id'], unique=False)
    op.create_index(op.f('ix_dataset_folder_files_mapping_file_id'), 'dataset_folder_files_mapping', ['file_id'], unique=False)
    op.create_index(op.f('ix_dataset_folder_files_mapping_dataset_id'), 'dataset_folder_files_mapping', ['dataset_id'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'parent_id', 'name', name=op.f('uq_user_parent_name'))
    )
    op.drop_index(op.f('ix_ingested_files_user_id'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_status'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_provider_hash'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_file_path'), table_name='ingested_files')
    op.drop_index(op.f('ix_ingested_files_dataset_id'), table_name='ingested_files')
    op.drop_table('ingested_files')
    # ### end Alembic commands ###
