"""initial

Revision ID: f09f8c95b82f
Revises: 
Create Date: 2026-07-16 15:11:52.630245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09f8c95b82f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    try:
        bind = op.get_bind()
        insp = sa.inspect(bind)
        if not insp.has_table("users"):
            op.create_table(
                "users",
                sa.Column("id", sa.String(36), primary_key=True),
                sa.Column("email", sa.String(255), nullable=False, unique=True),
                sa.Column("hashed_password", sa.String(255), nullable=False),
                sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
                sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
            )
        op.drop_index(op.f('ix_upload_responses_upload_id'), table_name='upload_responses', if_exists=True)
        op.drop_table('upload_responses', if_exists=True)
        op.drop_index(op.f('ix_upload_requests_upload_id'), table_name='upload_requests', if_exists=True)
        op.drop_table('upload_requests', if_exists=True)
        op.drop_column('users', 'is_active')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_table('upload_requests',
    sa.Column('upload_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filesize', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('upload_id', name=op.f('upload_requests_pkey'))
    )
    op.create_index(op.f('ix_upload_requests_upload_id'), 'upload_requests', ['upload_id'], unique=False)
    op.create_table('upload_responses',
    sa.Column('upload_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chunk_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_chunks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('merged_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('upload_id', name=op.f('upload_responses_pkey'))
    )
    op.create_index(op.f('ix_upload_responses_upload_id'), 'upload_responses', ['upload_id'], unique=False)
    # ### end Alembic commands ###
